lib/git/lib.rb

This makes it possible for developers to call Git.clone and include a `branch` in the `opts` hash.

Adding branch option support for #clone.

---

lib/git/diff.rb
tests/units/test_diff.rb

I was having trouble just getting the code to do a git diff without specifying commits.  
```
I, [2014-09-26T16:21:18.444662 #65864]  INFO -- : git diff '-p' 'HEAD' ''  2>&1
D, [2014-09-26T16:21:18.444727 #65864] DEBUG -- : fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/Users/fluong/.rvm/gems/ruby-2.0.0-p353/gems/git-1.2.8/lib/git/lib.rb:764:in `command': git diff '-p' 'HEAD' ''  2>&1:fatal: ambiguous argument '': unknown revision or path not in the working tree. (Git::GitExecuteError)
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
from /Users/fluong/.rvm/gems/ruby-2.0.0-p353/gems/git-1.2.8/lib/git/lib.r …
```

Git::Diff - don't convert to empty string if from/to is nil

---

git.gemspec

If you try to run the tests under test-unit ~>2.0 you will get a no
method error for teardown. This is apparently a test-unit 3.0 method as
upgrading test-unit fixed the error.

Test Unit needs specificity

---

tests/units/test_branch.rb

Just one additional assertion for `branch#create` to check that it does not switch branch (tests pass even when `git checkout -b` is used instead of `git branch`: https://github.com/schacon/ruby-git/pull/119)

additional test for branch#create method

---

lib/git/base.rb

When a submodule is cloned into another project, it has a different structure:
The .git folder is well, not a folder, it is a file that's sole contents
include a reference to where the .git folder for the submodule is on the
local drive.
Take that information from the .git *file* and then build our repository
and index location out of this.

Support Submodules

---

lib/git/diff.rb
lib/git/lib.rb

```ruby
repo.diff.name_status
#=> {"lib/git/lib.rb"=>"M"}
repo.diff('HEAD~3').name_status
#=> {"VERSION"=>"M", "git.gemspec"=>"M", "lib/git/config.rb"=>"M", "lib/git/lib.rb"=>"M", "tests/units/test_config.rb"=>"M", "tests/units/test_lib.rb"=>"M"}
repo.diff("HEAD~2", "HEAD~3").name_status
#=> {"VERSION"=>"M", "git.gemspec"=>"M"}
```

Adding `Git::Diff.name_status` support

---

.travis.yml
tests/units/test_archive.rb
tests/units/test_bare.rb

There were a few issues:
- The `tar xvpf` approach didn't work for me locally, supposedly since I run macOS, where `tar` prints its output to `stderr` by default. The workaround is to redirect `stderr` to `stdout` while running the command.
- The `tar` output also looked a bit different than before, so I changed it to use regexp matching instead of exact string matching (which is more fragile and prone to breakage.)
- The `parent.parent` stuff apparently returns different values now than before. I have really no clue why, but: I think it's better to accept that fact and merge this, so we can start validating the changes people have suggested now.
r? @rvodden

Fixed unit tests to run again

---

lib/git/lib.rb

Since GIT version 2.16.0 empty pathspecs as alias to "everything" has
been made illegal.
A more detailed study this change's impact has been made at:
https://github.com/ruby-git/ruby-git/issues/345#issuecomment-369260500
Closes #345

Fix ls-files for git 2.16

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_remotes.rb

I need to update the URL on remotes, which isn't currently possible with the library. This patch adds a simple version of that ability.

Enable set url on remotes

---

lib/git/lib.rb
tests/units/test_tags.rb

Passing a message when creating a tag erroneously prefixes the message with a space. This PR fixes that issue.

Fix space prefix in tag message

---

lib/git/lib.rb

Signed-off-by: Joshua Liebowitz
Looks like a copy paste error with the wrong block name.

config_get: Fix incorrect block name

---

lib/git/diff.rb

I'm heavy user of https://github.com/danger/danger and it internally uses this gem.
Danger frequently refers the `git diff`.
I noticed when `git diff` contains multi bytes text, the `full_diff_utf8_encoded` includes invalid chars like below.
I saw https://github.com/ruby-git/ruby-git/pull/276 and I could understand the background of the code.
The `command_lines` method had been fixed for it (https://github.com/ruby-git/ruby-git/commit/fe680f8c64d4b78280d541fe58e30ed1f3b9c6e0) but the `process_full_diff` had not.
Do not force to encode diff patch when the encoding type of it is UTF-8.

process_full_diff: Don't reencode diffs which are already UTF-8

---

.travis.yml

- Drop 1.9, 2.0 and 2.1 which are EOL
- Update 2.3, 2.4 and 2.5 specifiers (only specify minor version, not patch level)
- Update JRuby to use latest and greatest
Because this change is breaking in nature, **this will require a major version bump** to comply with SemVer guidelines.

.travis.yml: Update supported Ruby versions

---

lib/git/lib.rb

I needed to delete a remote branch. And the way to do it is by using the `--delete` argument in the `git push` command [(as seen in the Git docs)](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches#_delete_branches).

Add support for '--delete' in push

---

lib/git/lib.rb
lib/git/stashes.rb
tests/units/test_stashes.rb

using File as a block so that it tears down once everything has completed - We operated on the each and left the file descriptor open.
adding a API directly in stashes
adding testing around it.
fixes #312

fixing file descriptor leakage

---

.jrubyrc
.travis.yml

I am adding ruby-head (allows failure) and ruby 2.6 which is in its second preview which should be a release candidate soon if following Ruby's release patterns.
Removing .jrubyrc from the repo as jruby has deprecated C ext support from the the library as of 1.7 and we are testing at 9.2 (Ruby 2.5 equiv.).
Source: 
https://github.com/jruby/jruby-cext#status
https://twitter.com/headius/statuses/281091403919003649
Removing the before_install section as all of those steps are standard parts of Travis CI and appear under the `ruby.versions` section.

Adding ruby-head and ruby 2.6 to Travis, removing C ext from repo

---

README.md
lib/git/base/factory.rb
lib/git/lib.rb
tests/units/test_merge_base.rb

Add support for `git merge-base`, which finds as good common ancestors as possible for a merge
Usage example:
`g.merge_base('branch1', 'branch2', ..., options)`
Possible options:
```ruby
{
all: true,
octopus: true,
fork_point: true,
independent: true
}
```
The method returns an array of `Git::Object::Commit`. The amount of items depends on the particular case

Support merge-base

---

README.md
lib/git/config.rb
tests/units/test_config.rb

By adding a new environment variable called `GIT_PATH` we can allow
consumers, that is, a user of a gem that the gem itself uses the git gem,
to customize the location of the git binary.
Example: Having a gem called `git-tool` that uses this gem `git`, if I,
as a user wants to modify the git bin location, I could do:
```
GIT_PATH=/foo/bin git-tool bar
```
Signed-off-by: Salim Afiune <afiune@chef.io>

Allow consumers to point git binary via env var

---

.github/stale.yml

The previous settings have annoyed people, as indicated by #432. Let's try to find a more balanced, sensible approach.
(Greatly inspired by @junaruga's change in another project: https://github.com/rack-test/rack-test/pull/254. In fact, I copied the `stale.yml` file from that project verbatim. :see_no_evil:)

Fix Stalebot settings to not auto-close old issues/PRs

---

CHANGELOG.md
lib/git/version.rb

Bump version to build a 1.6.0.pre1 release.
This is in preparation for the 1.6.0 release.  Since it has been a while since the last release ([1.5.0](https://github.com/ruby-git/ruby-git/releases/tag/v1.5.0) Aug 18th, 2018), we have decided to put out a pre-release version of this gem (1.6.0.pre1) for people to test.
The maintainers will need to determine the release criteria for 1.6.0 and communicate this to the community in issue #434.
My hope is that after the 1.6.0 release, we can start to accept all the great contributions people have made.

Update version for 1.6.0.pre1 pre-release

---

lib/git.rb

`VERSION` was previously defined in `lib/git.rb`. It was moved into `lib/git/version.rb` in commit a308cc9, but the file was not required.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the
best of my knowledge, is covered under an appropriate open
source license and I have the right under that license to
submit that work with modifications, whether created in whole
or in part by me, under the same open source license (unless
I am permitted to submit under a different license), as
Indicated in the file; or
(c) The contribution was …

Include version.rb, providing Git::VERSION

---

lib/git/branch.rb

This change fixes the warning:
Users/USER/rvm/gems/ruby-2.7.0-rc1@ruby2.7-no-rails/gems/git-1.5.0/lib/git/branch.rb:40:
warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
This fix was originally proposed by @jasnow

Removed blank after method name to fix warning

---

PULL_REQUEST_TEMPLATE.md

This PR fixes the broken link to `CONTRIBUTING.md` in a PR template.

fix broken link in a PR template

---

PULL_REQUEST_TEMPLATE.md

🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.
This PR changes a relative link to an absolutely link.
Please see https://github.com/ruby-git/ruby-git/pull/444#issuecomment-581560817 .

fix broken link in a PR template again

---

lib/git/lib.rb
tests/units/test_logger.rb

Similar to #30 I just found an issue with `ruby-git` when trying to match the string returned from `current_branch` with e.g. `"master"`. I just recently found this issue and I guess it's related to a recent update of my `git` on my machine which came in just recently.
* `git@2.24.0.windows.2` 
* `ruby-git@1.5.0` (also had `1.3.0` before - same issue)
* `ruby@2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]`
```ruby
$ irb
irb(main):002:0> require 'git'; git = Git.open '.'; git.current_branch
master
=> "\e[32mmaster\e[m"
```
Hence, `"\e[32mmaster\e[m"` is not equal to `"master"`.
`git.current_branch` should return the string of the current branch without coloring.
In fact, the underlying run of `git branch` should include `--no-color` option (which is a nested call inside …

`current_branch` contains color escape codes

---

lib/git/lib.rb
tests/units/test_logger.rb

- [*] Ensure all commits include DCO sign-off.
- [*] Ensure that your contributions pass unit testing.
- [*] Ensure that your contributions contain documentation if applicable.
This code call Ruby warning:
```
return str.encode(default_encoding, str.encoding, encoding_options) if str.valid_encoding?
```
@see https://piechowski.io/post/last-arg-keyword-deprecated-ruby-2-7/
Signed-off-by: Sergey Blohin <sblohin@yandex.ru>

Fix Ruby 2.7 Deprecation Warning About Keyword Args

---

lib/git/lib.rb
tests/test_helper.rb

I made these changes while preparing a new upload of ruby-git for Debian.
The last commit is not necessarily related to supporting the new git and ruby, but it has no effect for upstream developers while making the life of downstream maintainers easier. Please consider accepting it as well, but if not I can drop it from this PR.

Add support for git 2.25 and ruby 2.7

---

lib/git/lib.rb

`Git::Lib#normalize_encoding`: when checking to see if the given string
is already in the desired encoding, fix the comparison check to compare
string value to string value, not class to string value.

Git::Lib#normalize_encoding early return fix

---

tests/files/working/dot_git/config

If a user has GPG signing set to true in their global `.gitconfig` file, the test suite will fail. This is because the test suit now includes a check of a commit message (the `test_commit_with_no_verify` test in `tests/units/test_lib.rb` that was added by #454) but did not update the test config file. This commit updates the config file to set the `gpgsign` option to false.

Disable GPG Signing in Test Config

---

lib/git/lib.rb
tests/units/test_commit_with_empty_message.rb
tests/units/test_log.rb

If the commit doesn't contain a message, parsing the output of "git log"
results in an error, which occures because the end of the commit message
can't be detected.
fixes #481

Add commit --allow-empty-message option and fix empty message parsing in process_commit_log_data

---

.travis.yml
git.gemspec
lib/git/base.rb
lib/git/lib.rb
tests/test_helper.rb
tests/units/test_archive.rb
tests/units/test_diff_non_default_encoding.rb
tests/units/test_git_path.rb
tests/units/test_init.rb
tests/units/test_lib.rb
tests/units/test_logger.rb
tests/units/test_worktree.rb

Please describe your pull request.
Hi, I encountered an issue with using git gem (via jeweler gem) on Windows running in JRuby. 
```
Git::GitExecuteError: git '-c' 'color.ui=false' version   2>&1:git: ''-c'' is not a git command. See 'git --help'.
C:/Users/User/code/ruby-git/lib/git/lib.rb:989:in `command'
C:/Users/User/code/ruby-git/lib/git/lib.rb:895:in `current_command_version'
C:/Users/User/code/ruby-git/lib/git/lib.rb:905:in `meets_required_version?'
C:/Users/User/code/ruby-git/lib/git.rb:26:in `<main>'
```
It turns out it was not escaping strings properly because it was running in JRuby instead of CRuby, thus not detecting Windows correctly via …

JRuby on Windows

---

lib/git/lib.rb
tests/units/test_lib.rb

This bunch of commits does some refactoring and adds a way to optionally disable chomping the output of commands.
This fixes #347 in respect to the `#show` method.  Other methods may need similar adjustment.

Do not always chomp output

---

lib/git/lib.rb

Fix Ruby 2.7.x keyword arg deprecation warning introduced in PR #368

Fix Ruby 2.7.x keyword arg deprecation warning introduced in PR #368

---

lib/git.rb
lib/git/lib.rb
tests/units/test_lib.rb

Allow passing `--refs` to `ls-remote`
The default behavior of ls-remote shows dereferenced tags 
Including on this very repo. Try `$ git ls-remote https://github.com/ruby-git/ruby-git.git` and get `^{}` at the end of dereferenceable tags:
```
...
99b11561a64740285872f4c0a8b72e3e69308ed2        refs/tags/v1.2.9^{}
4bc7f14b62714853c1bd0c53930172356116e6a1        refs/tags/v1.2.9.1
cc6d6efc1b7eaf63609c4c06969b0f839dc80095        refs/tags/v1.2.9.1^{}
03524b251812019da4fed3fc7d6c835f03f47c3d        refs/tags/v1.3.0
a223fcf873bd99658cd1d0bdee1818adc7e3e92c        refs/tags/v1.3.0^{}
...
```
If one is only interested in tags, the dereferenceable tags get in the …

Allow users to provide '--refs' to 'ls-remote'

---

lib/git/base.rb
tests/test_helper.rb
tests/units/test_git_dir.rb

`index` when not given, defaults to `"#{work_tree}/.git/index"`.  This only works as long as `git_dir` is `"#{work_tree}/.git"`. In the general case, the `index` default should be `#{git_dir}/index`.
This PR adds two tests:
* `TestGitDir#test_index_calculated_from_git_dir` which tests that `index` is calculated correctly when `git_dir` is not `"#{work_tree}/.git/index"`
* `TestGitDir#test_git_dir_outside_work_tree` which tests that when `git_dir` is in a non-standard location, Git.open and option functions work.
Fix the case in `Base#open` where the `--git-dir` is a file as is the case with Submodules and (non-main) Worktrees.  This case was handled for …

Calculate the default for index relative to git_dir instead of work_tree

---

lib/git/lib.rb

The JRuby build on Windows fails because `#chomp!` is called on an IO object.  When a block is passed to `#command`, `output` is an `IO` object instead of a `String` (this is done in `#run_command`).  Create a special case to not call `#chomp` when a block is passed to `#command`.

Fix JRuby Build on Windows

---

lib/git/lib.rb
tests/units/test_status.rb

According to the [git-diff-index docs][1], git commands like diff-index
and diff-files typically don't look at the actual contents of files in
the working tree. This means that these commands can be easily fooled by
operations that don't change the content of a file such as deleting and
recreating it, or even running `touch` on a file.
The docs then say that one may update the index to make it be in sync
with the actual contents of the working directory. The recommended
command would seem to be `git update-index --refresh`, but in my
testing, this caused "needs update" errors in some of the tests. So I've
resorted to using `git status`, which is probably a slightly more
heavyweight command, but does pass the tests.
If this is a concern, an alternative approach might be to specifically …

Update index before fetching modified files

---

README.md
lib/git/base.rb
lib/git/lib.rb
tests/units/test_init.rb

Add new `:log` option log to Git.clone which logs the clone operation and returns the new Git::Base object with its logger set to the value passed in `:log`.

Allow a logger to be passed to Git.clone

---

.gitignore
.yardopts
CHANGELOG.md
CONTRIBUTING.md
MAINTAINERS.md
README.md
RELEASING.md
Rakefile
git.gemspec
lib/git.rb
lib/git/base.rb
lib/git/base/factory.rb
lib/git/lib.rb

Create YARD documentation for ruby-git instead of rdoc. Make improvements to the documentation.
Not everything is documented yet. Additional PRs will add YARD doc for everything.
The work done so far shows what this would look like for most methods in the Git module like Git.bare, Git.open, Git.clone, Git.init.
In order to see this updated documentation, you will need to clone this PR branch and then run:
```
bundle install
bundle exec rake yard && open doc/index.html
```
This project uses the `redcarpet` gem to be able to use Markdown to format YARD documentation.  `redcarpet` is not compatible with JRuby.
To make this clear, the rake tasks for YARD …

Add YARD documentation to ruby-git

---

git.gemspec

Since files included in the gem were explicitly listed in the gemspec, it was easy to forget when a new file should be added to the gem.  This change automatically includes all files except for tests into the gem.
Fixes #506

Add all appropriate files (excluding tests) to the gem

---

.github/workflows/continuous_integration.yml
CONTRIBUTING.md
Rakefile

The current CI build runs the unit tests but does not actually build the gem, install it, or try to use the gem that was built to make sure it was built correctly.
This change is meant to stop issues like the one reported in #506 from being published as a gem.
This change addresses all that by:
* Updating the `default` Rake task to build the gem.
* Adding a new Rake task `test:gem` that installs the gem and runs a sanity test using the installed gem.
* Add a new step to the CI build that runs the `test:gem` rake task.

Add gem build, install, and sanity test to the CI build

---

Rakefile

In PR #509, a workaround was created because of a bug in JRuby (see jruby/jruby#6516).  That bug has since been fixed. This PR removes the workaround.

Remove JRuby on Windows workaround

---

tests/units/test_show.rb

Refs #503
Ensure that the fix for the bug reported in #503 is not reverted.

test: git show should not chomp results

---

lib/git/base.rb

This PR fixes a minor oversight in the text spacing.

Fix use of spaces instead of tab in lib/git/base.rb

---

README.md

In my opinion .current_branch is a fairly common operation, and it would be nice to have it listed on the readme file.

Add "g.current_branch" to Readme.md

---

lib/git/lib.rb

This pull request add and option on `opts` hash to sign your commits using the default key that has been set in the config file

feat: add --gpg-sign option on commits

---

tests/units/test_worktree.rb

This is a fix for running unit tests on Mac where /tmp is actually a symlink to /private/tmp. `Git#dir` returns the directory you give it and `Worktree#dir` returns the expanded path since that is what `git workspace list` returns.
Some additional thought will have to be put into considering if `Git#dir` should also return the expanded path.

Fix worktree test when git dir includes symlinks

---

README.md
lib/git/lib.rb
tests/units/test_commit_with_gpg.rb

When support for the `gpg_sign` option was added to the `Git::Lib#commit` in #518, it did not actually work properly for the case of the key being passed into the commit command.
This PR does the following:
* Correctly allows specification of a GPG Key in the `gpg-sign` option as follows:
```Ruby
key_id = '0A46826A'
g.commit('message', gpg_sign: key_id)
```
* Add tests to make sure the commit command line is built correctly for the two use cases of gpg_sign.
* Add examples in the `README.md`
This fix also fixes the warning introduced in #518 the was output by Ruby when requiring the `git` gem:
```
$ irb …
```

Fix the gpg_sign commit option

---

tests/units/test_worktree.rb

... otherwise the test fails with:
```
TestWorktree:
test_worktree_add_and_remove:				.: (0.080734)
test_worktree_prune:					.: (0.055268)
test_worktrees_all:					.: (0.037409)
test_worktrees_single:				E
===============================================================================
Error: test_worktrees_single(TestWorktree): NameError: uninitialized constant TestWorktree::Pathname
/<<PKGBUILDDIR>>/tests/units/test_worktree.rb:51:in `test_worktrees_single'
48:
49:   def test_worktrees_single
50:     worktree = @git.worktrees.first
=> 51:     git_dir = Pathname.new(@git.dir.to_s).realpath.to_s
52:     assert_equal(worktree.dir, git_dir)
53:     assert_equal(worktree.gcommit, SAMPLE_LAST_COMMIT)
54:   end
===============================================================================
: …
```

Require pathname module

---

lib/git/lib.rb
tests/units/test_merge.rb

Docs at:
https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---no-commit
Signed-off-by: Jon Dufresne <jon.dufresne@gmail.com>

Add support for the `git merge --no-commit` argument

---

lib/git.rb
lib/git/base.rb
lib/git/lib.rb
tests/units/test_init.rb

Signed-off-by: Jon Dufresne <jon.dufresne@gmail.com>
Please describe your pull request.

Add support for `git init --initial-branch=main` argument

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_index_ops.rb

From `git clean --help`:
> Git will refuse to modify untracked nested git repositories (directories with a .git subdirectory) unless a second -f is given.
This adds the ability to pass `-ff` to `git clean` to enable removing directories with a .git subdirectory.
An example use case is when a gem from a git source is cached in vendor/cache/some_gem. Removing would require `git clean -dff`

Add -ff option to git clean

---

lib/git/base.rb
tests/units/test_init.rb
tests/units/test_thread_safety.rb

When opening a submodule or secondary working tree which exist in a directory different than the current directory, the command would fail. Fixes #541.
The logic for how to set working tree, repository, and index directories is scattered all over the place. This PR tries to centralize that logic.
The PR also fixes a bug where a new `Git.init` was creating a new bare repository in the `.git` directory of the given directory rather than directly in the given directory. That is the reason the tests needed to be changed.

Refactor how working, repository, and index directories are initialized

---

Dockerfile.changelog-rs
RELEASING.md

I don't use Rust so it seems like everytime I need to generate a change log with `changelog-rs`, I have to remember to install Rust, install `changelog-rs`, and remember how to use it.
This PR adds a Dockerfile and instructions to run `changelog-rs` so you don't have to install Rust or the changelog-rs command.
To Build the changelog-rs docker image, run this command from this project's root directory:
```Shell
docker build --file Dockerfile.changelog-rs --tag changelog-rs .
```
To use this image to output a changelog, run the following command from the project's root directory.  Substitute the appropriate …

Create a Docker image to generate the release change log

---

.github/workflows/continuous_integration.yml

Add Ruby 3.0 to CI build

---

lib/git/lib.rb
tests/units/test_windows_cmd_escaping.rb

This PR addresses issue #495.
On windows, double quotes in shell command arguments should be escaped.

Properly escape double quotes in shell commands on Windows

---

tests/units/test_git_dir.rb
tests/units/test_lib.rb

Two tests emit unnecessary output while running. This PR removes this particular test output.

Suppress unneeded test output

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.10.2...HEAD)
* 292087e Supress unneeded test output (#570)
* 19dfe5e Add support for fetch options "--force/-f" and "--prune-tags/-P". (#563)
* 018d919 Fix bug when grepping lines that contain numbers surrounded by colons (#566)
* c04d16e remove from maintainer (#567)
* 291ca09 Address command line injection in Git::Lib#fetch
* 521b8e7 Release v1.10.2 (#561)
DO NOT MERGE THIS PULL REQUEST VIA THE GITHUB UI
* Get someone to review and approve the release pull request
* Merge the pull request manually from the command line with the following commands:
```Ruby
git checkout master
git merge …
```

Release v1.11.0

---

Gemfile

This PR fixes the ruby-head build (Ruby 3.2) which fails because `yard` calls Ruby's `taint` API. lsegal/yard#1419 fixes this issue in `yard` which was merged months ago but there has not yet been a new release of `yard`.
Rather than live with the `ruby-head` builds failing for the `git` gem, this PR installs `yard` from the Github `main` branch. This is a temporary work around which should be removed after `yard` releases a new version that includes the fix for `taint`.
More info on the `taint` API in Ruby:
In Ruby 2.7, the taint checking mechanism [was removed](https://bugs.ruby-lang.org/issues/16131). …

Fix build on Ruby 3.2

---

README.md
lib/git.rb
lib/git/base.rb
lib/git/lib.rb
tests/units/test_git_clone.rb

Make the `directory` parameter to `Git.clone` optional. By default, (command line) `git` will assign the directory to clone to.
A call to `Git.clone` before this change required the `directory` param (aka param 2):
```ruby
Git.clone('https://github.com/ruby-git/ruby-git.git', 'ruby-git') # clones to ./ruby-git
```
This PR enables leaving off the second argument:
```ruby
Git.clone('https://github.com/ruby-git/ruby-git.git') # also clones to ./ruby-git
```
Fixes #565

Make the directory param to Git.clone optional

---

.github/workflows/continuous_integration.yml

This is a workaround for the problem in JRuby with the JDK being used as described in jruby/jruby#7182 where it is report that there is a bug in the JDK that causes JRuby to raise an error when opening the NULL device for write. The underlying JDK bug is reported and fixed in [JDK-8285445](https://bugs.openjdk.java.net/browse/JDK-8285445) which is targeted to a July 2022 release.
In the meantime, the workaround adds the following environment variable `JAVA_OPTS: -Djdk.io.File.enableADS=true` to all build steps so JRuby can function. This setting is detailed in the [JDK Patch 8u333 Release …

Workaround to get JRuby build working

---

README.md
lib/git/base.rb
lib/git/lib.rb
tests/test_helper.rb
tests/units/test_remotes.rb

The fix for https://github.com/advisories/GHSA-69p6-wvmq-27gg broke a workflow for some folks (like @matthewriedel-flux) by removing the ability to fetch all remotes.
This adds --all to the list of available flags for the #fetch method. It does not add :a as an alternative flag, as git fetch -a and git fetch --all are not the same thing.
This PR builds on the work by @matthewriedel-flux in PR #579.  This PR adds tests to make sure that the git-fetch command line is built properly based on the opts passed to Git::Base#fetch.  Additionally, this PR allows leaving off the remote arg as follows:
```ruby …
```

Support the --all option for Git::Base#fetch

---

tests/units/test_lib.rb

When testing `git commit --no-verify`, the `pre-commit` script was created in such a way that failed on the current Windows build configuration. This change creates the file properly with the `#!/bin/sh` hash bang to ensure the script runs on all platforms including Windows.

Fix windows build

---

.github/workflows/continuous_integration.yml

It would be nice to be able to run the `master` branch build to see if it is still working even though gem dependencies or latest OS versions were updated.
With this change, the build can be triggered from [the CI workflow on the GitHub actions page for this repository](https://github.com/ruby-git/ruby-git/actions/workflows/continuous_integration.yml)

Allow the CI build to be run manually using the GitHub interface

---

Gemfile
git.gemspec

This PR reverses the changes made in #573 which installed the yard gem from the GitHub `main` branch instead of pulling the gem from rubygems. See #573 for why this was done.
`yard-0.9.8` has the fix for the `Object#taint` call that was failing the build on Ruby 3.2.

Use yard gem version 0.9.8 or later

---

README.md
lib/git/lib.rb
tests/units/test_commit_with_gpg.rb

Add the ability to send the `--no-gpg-sign` option to git. This is the default behavior in a "vanilla" git install, but if gpg signing is configured elsewhere (i.e. in `~/.gitconfig`) then you can use this option to override and disable it for a particular commit.
Triggered by `gpg_sign: false` - see test and README updates.

Support the commit --no-gpg-sign flag

---

lib/git.rb
lib/git/lib.rb
tests/all_tests.rb
tests/units/test_lib_meets_required_version.rb

Fixes #564.
Does not fetch the current git version number until a Git::Lib instance is created. This avoids creating threads to shell out commands during code loading which caused autoload to break.

Fix exception when Git is autoloaded

---

tests/units/test_init.rb

Fix test case by extracting `init.defaultBranch` into variable
https://github.com/ruby-git/ruby-git/issues/587

Do not assume the default branch is 'master' in tests

---

README.md
lib/git/lib.rb
tests/units/test_lib.rb

This adds support for `start-point` git option when creating a new branch during checkout.
Fixes https://github.com/ruby-git/ruby-git/issues/249

Add start_point option for checkout command

---

lib/git/lib.rb
tests/units/test_ls_files_with_escaped_path.rb

In `Lib#ls_files`, do not use `eval` to unescape paths. Instead, use `Git::EscapedPath` to unescape the path.

In ls-files do not unescape file paths with eval

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.12.0...v1.13.0)
* 8349224 Update list of maintainers (#598)
* 4fe8738 In ls-files do not unescape file paths with eval (#602)
* 74b8e11 Add start_point option for checkout command (#597)
* ff6dcf4 Do not assume the default branch is 'master' in tests
* 8279298 Fix exception when Git is autoloaded (#594)

Release v1.13.0

---

.github/workflows/continuous_integration.yml

Drop the ruby-2.3 build from the GitHub actions build. Add ruby-3.1 and ruby3.2 builds.

Drop ruby-2.3 CI build and add ruby-3.1 and ruby-3.2 CI builds

---

lib/git/lib.rb
tests/units/test_lib_meets_required_version.rb

FIXES #604 
If git was built from source, the version output from the `git version` command is as follows:
```shell
$ git version
git version 2.39.GIT
$
```
In this case, calling Git::Lib#current_command_version causes the following error whenever the a Git::Lib object is created:
```
../.local/share/gem/ruby/3.0.0/gems/git-1.13.0/lib/git/lib.rb:1034:in current_command_version': undefined method split' for nil:NilClass (NoMethodError)
```
This PR relaxes the requirement such that a version number of '2.39.GIT' returns a version array [2, 39, 0].
The following changes were made in this PR:
* …

Fix version parsing

---

.github/workflows/continuous_integration.yml
RELEASING.md

This change removes the following build warning:
[Ruby 3.2 on ubuntu-latest](https://github.com/ruby-git/ruby-git/actions/runs/3906105562/jobs/6673899529)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Update the GitHub Action step "actions/checkout" from v2 to v3

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.13.0...v1.13.1)
* 667b830 Update the GitHub Action step "actions/checkout" from v2 to v3 (#608)
* 23a0ac4 Fix version parsing (#605)
* 429f0bb Update release instructions (#606)
* 68d76b8 Drop ruby 2.3 build and add 3.1 and 3.2 builds (#607)

Release v1.13.1

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.13.1..v1.13.2)
Changes since v1.13.1:
* b6e031d Fix `Git::Lib#commit_data` for GPG-signed commits (#610)
* b12b820 Fix escaped path decoding (#612)

Release v1.13.2

---

lib/git/lib.rb
tests/units/test_lib.rb
tests/units/test_logger.rb

In order to support moving to using a spawn like interface for calling git commands in a subprocess (rather than backticks), make the following changes to Git::Lib#command:
* Collapse the `cmd` parameter and the `opts` parameter into a single Array<String> parameter named `cmd`
* Do not allow the `cmd` parameter to have nested arrays. Enforce that it is an Array of Strings only by raising an `ArgumentError` when `cmd` is anything other than an Array of Strings.
* Options that apply to how `#command` works (and are not passed on to the git command like `redirect` and `chomp`) should be passed as keyword parameters to `#command` instead of a Hash at the end …

Internal refactor of Git::Lib command

---

lib/git/base.rb
lib/git/lib.rb
tests/test_helper.rb
tests/units/test_init.rb

Rather than allow the logger to be nil which requires special casing it use, create a null logger with `Logger.new(nil)` which gives a functional logger object that does not log anything.
This should make the code a little less complex.

Create a null logger if a logger is not provided

---

bin/test

To avoid warnings about init.defaultBranch not being set when running tests, set the default to `master`.
The actual value does not matter for the tests, but something needs to be set to avoid the warning.

Set init.defaultBranch when running tests if it is not already set

---

tests/units/test_archive.rb

Use `Dir::Tmpname.create` to get a name of a temporary file instead of creating the file with `Tempfile.new`. 
Also, each test should clean up manually after itself rather than having the complexity of keeping track of temp files and deleting them in the `#cleanup` method.

Simplify how temp files are used when testing Git::Base#archive

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_lib.rb

This PR adds`extended_regexp` as a passable option, and allows multiple path limiters to be used. I think the additions are fairly self-explanatory, but happy to answer questions if need be.

grep: Allow the use of an array of path limiters and extended_regexp as an available option.

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.13.2..v1.14.0)
Changes since v1.13.2:
* 0f7c4a5 Allow the use of an array of path_limiters and add extended_regexp option to grep (#624)
* 8992701 Refactor error thrown when a git command fails (#622)
* cf74b91 Simplify how temp files are used when testing Git::Base#archive (#621)
* a8bfb9d Set init.defaultBranch when running tests if it is not already set (#620)
* 9ee7ca9 Create a null logger if a logger is not provided (#619)
* 872de4c Internal refactor of Git::Lib command (#618)
* 29e157d Simplify test running and fixture repo cloning (#615)
* 08d04ef Use dynamically-created repo for signed commits test (#614)

Release v1.14.0

---

lib/git/branch.rb
lib/git/lib.rb
tests/units/test_branch.rb

Fixes #599
Fixes #600 
`Git::Branch#update_ref` creates the wrong ref name, resulting in "refname is ambiguous" warnings. For instance, when updating an existing branch named 'testing' with the following code:
```Ruby
git.branch('testing').update_ref(git.revparse('HEAD'))
```
Creates a new file `.git/testing` instead of updating the file `.git/refs/heads/testing`.

Fix Git::Branch#update_ref

---

lib/git/base.rb
tests/units/test_init.rb

This change allows giving `Git.open(path)` a path that isn't the root repository directory. `Git.open` will use the top-level directory of the working tree containing `path`.
Fixes #596.

Allow a repo to be opened by giving a non-root repo directory

---

README.md
lib/git/lib.rb
lib/git/log.rb
tests/units/test_log.rb

Fixes #466 
Add ability to pass the `--all` option to `git log` as follows:
```ruby
git.log.all
```
Passing a non-integer value as the `count` parameter to `Git::Base#log` will raise a `ArgumentError` when the log is run:
```ruby
max_count = 'a'
git.log(max_count).size
lib/git/lib.rb:1186:in `log_common_options': The log count option must be an Integer but was "a" (ArgumentError)
```

Add Git::Log#all option

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_rm.rb

Calling `Git::Lib#remove` with `recursive` or `cached` option causes nested array assignment to `cmd` argument of `Git::Lib#command` and throws exception.
It is caused by passing an array to `Array#<<`.
fix #631

Fix error when calling `Git::Lib#remove` with `recursive` or `cached` options

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_pull.rb

Fixes #423 
`Git::Lib#pull` with no args currently performs `git pull origin master`. It sets the remote name to 'origin' and the branch to pull to 'master'.  This probably isn't what the user expects and can cause errors or undesired results.
`git pull` with no args figures out defaults for the remote name and branch name to use. `Git::Lib#pull` should have the same effect.

#pull with no options should do the same thing as `git pull` with no options

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.14.0..v1.15.0)
Changes since v1.14.0:
* b40d #pull with no options should do the same thing as `git pull` with no options (#633)
* 9c5e Fix error when calling `Git::Lib#remove` with `recursive` or `cached` options (#632)
* 806e Add Git::Log#all option (#630)
* d905 Allow a repo to be opened giving a non-root repo directory (#629)
* 1ccd Rewrite worktree tests (#628)
* 4409 Fix Git::Branch#update_ref (#626)

Release v1.15.0

---

CONTRIBUTING.md
bin/test

Building upon #615, make it so that tests can be run without specifying the directory:
```shell
$ bin/test test_archive
...
$ bin/test test_archive test_object
...
$ bin/test
...
```

Make it easier to run test files from the command line

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_push.rb

`Git::Lib#push` with no args currently performs `git push origin master`. It sets the remote name to 'origin' and the branch to pull to 'master' (even if there is no branch named 'master').  This probably isn't what the user expects and can cause errors or undesired results.
`git push` with no args figures out defaults for the remote name and branch name to use. `Git::Lib#push` should have the same behavior.

#push without args should do same as `git push` with no args

---

lib/git/base/factory.rb
tests/units/test_branch.rb

Currently, when getting a branch, the default branch name returned is 'master' even if no branch of that name exists.
This PR changes the behavior of Git::Lib#branch to use the current branch name instead of 'master' as a default.

`#branch` name should default to current branch instead of `master`

---

lib/git/remote.rb
tests/units/test_remotes.rb

This PR makes two changes:
1. `Remote#branch` when not given a branch name will create a Branch object representing the remote tracking branch with the same name as the current branch. Originally, the default was `master` even if a branch of that name did not exist.
2. `Remote#merge` when not given a branch name will merge from the remote tracking branch with the same name as the current branch. Before this PR, merge would try to merge from the remote `master` branch even if that branch did not exist.

`Remote#branch` and `#merge` should default to current branch instead of `master`

---

lib/git/lib.rb
tests/units/test_branch.rb

Fixes #510 
When in a detached head state in any worktree, `Git::Base#branches` would raise an error because it is unable to parse the output from `git branch -a` in this condition.
This PR changes the parsing code to account for this situation.

Fix parsing when in detached HEAD state in Git::Lib#branches_all

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.15.0..v1.16.0)
Changes since v1.15.0:
* 536d Fix parsing when in detached HEAD state in Git::Lib#branches_all (#641)
* 5c68 Fix parsing of symbolic refs in `Git::Lib#branches_all` (#640)
* 7d88 Remote#branch and #merge should default to current branch instead of "master" (#639)
* 3dda0 `#branch` name should default to current branch instead of `master` (#638)
* d33d #checkout without args should do same as `git checkout` with no args (#637)
* 0c90 #push without args should do same as `git push` with no args (#636)
* 2b19 Make it easier to run test files from the command line (#635)

Release v1.16.0

---

README.md
lib/git.rb
lib/git/base.rb
lib/git/lib.rb
tests/units/test_git_default_branch.rb
tests/units/test_lib_repository_default_branch.rb

Implements `Git.default_branch(repository)` which returns the default branch of a repository where repository can be a URI or a Pathname.
For instance:
```ruby
require 'git'
Git.default_branch('https://github.com/ruby-git/ruby-git') #=> 'master'
Git.default_branch('https://github.com/rspec/rspec-core') #=> 'main'
```
Can also be used on a local repository by giving a path to the repository. In this case, it returns the branch being tracked by refs/remotes/origin/HEAD if it exists. If not, it returns the current branch.
```ruby
require 'git'
Git.default_branch('.') #=> 'master'
```

Get default branch of remote repository (Git.default_branch)

---

lib/git/lib.rb
tests/test_helper.rb
tests/units/test_ls_tree.rb

Fixes #475
[git-ls-tree](https://git-scm.com/docs/git-ls-tree) returns three types of objects: `commits`, `blobs` and `trees`. `git ls-tree` returns a commit in place of a submodule tree to indicate the commit SHA in the submodule's repository that is linked into the containing repository.
The implementation of `Git::Lib#ls_tree` raised an error when `git ls-tree` returns a `commit`. This PR changes the implementation so that the commit is returned in the Hash returned (from the test case):
```ruby
{
"blob" => {
".gitmodules" =>{ mode: "100644", sha: "caff6b7d44973f53e3e0cf31d0d695188b19aec6" },
"README.md" => { mode: "100644", sha: …
```

Make Git::Base#ls_tree handle commit objects

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_push.rb

Add the ability to specify `--push-option` args to the `git push` command (see [git-push](https://git-scm.com/docs/git-push) for details).
Either a string or an array may be passed:
```ruby
git.push(push_option: 'foo') 
git.push(push_option: ['foo', 'bar', 'baz'])
```

Add the push_option option for Git::Lib#push

---

README.md
Rakefile
git.gemspec
lib/git.rb
tests/test_helper.rb
tests/units/test_git_deprecation.rb

Deprecation warnings are managed with the `Git.deprecation` attribute.
Use this object to define deprecations in the source code:
```ruby
Git.deprecation.deprecate_methods(Git::Branch, stashes: 'use Git::Base#stash_list instead')
```
The default action when using deprecated items (methods, classes, etc.) is to output
a **DEPRECATION WARNING** to `$stderr` like the following:
```text
DEPRECATION WARNING: stashes is deprecated and will be removed from git 2.0.0 (use Git::Base.stash_list instead)
```
The action taken when a deprecated item is used is defined by setting the behavior
on the deprecation object:
```ruby
Git.deprecation = :stderr
Git.deprecation = …
```

Add deprecation mechanism (introduces runtime dependency on ActiveSupport)

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.16.0..v1.17.0)
Changes since v1.16.0:
* 1311 Add deprecation mechanism (introduces runtime dependency on ActiveSupport) (#645)
* 50b8 Add the push_option option for Git::Lib#push (#644)
* a799 Make Git::Base#ls_tree handle commit objects (#643)
* 6db3 Implememt Git.default_branch (#571)

Release v1.17.0

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.17.0..v1.17.1)
Changes since v1.17.0:
* 774e Revert introduction of ActiveSupport dependency (#649)

Release v1.17.1

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.17.1..v1.17.2)
Changes since v1.17.1:
* f43d6 Fix branch name parsing to handle names that include slashes (#651)

Release v1.17.2

---

README.md
lib/git.rb
lib/git/lib.rb
tests/units/test_git_clone.rb

Currently, `Git.clone` only allows setting a single config variable via the `:config` option. This option is given as a string as follows:
```ruby
Git.clone(uri, destination, { config: 'submodule.recurse=true' }
```
This PR allows an Array to be given for `:config` (in addition to still supporting the single String value):
```ruby
g = Git.clone(
uri, destination,
:config => [
'core.sshCommand=ssh -i /home/user/.ssh/id_rsa',
'submodule.recurse=true'
]
)
See [git-clone --config](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt--cltkeygtltvaluegt) for more details.

Update Git.clone to set multiple config variables

---

tests/test_helper.rb
tests/units/test_submodule.rb

There was no test that ensured that `Git.open` works for submodules. This PR adds two tests:
* test that a submodule can be opened from its root directory
* test that a submodule can be opened from a subdirectory within the submodule
This supersedes #488

Add test to ensure that `Git.open` works for submodules

---

lib/git/failed_error.rb
tests/units/test_failed_error.rb

Include command line output in command result instead of just stderr. This gem currently redirects stderr to stdout so the reported error message was always blank.
Thanks @alexjfisher

Correctly report command output when there is an error

---

Rakefile

When building YARD documentation using TruffleRuby-head, the following error occurs which fails the build:
```shell
[warn]: Syntax error in `lib/git/lib.rb`:(695,11): _1 is reserved for numbered parameter
[20](https://github.com/ruby-git/ruby-git/actions/runs/4380304214/jobs/7667220593#step:4:21)
[warn]: ParserSyntaxError: syntax error in `lib/git/lib.rb`:(695,11): _1 is reserved for numbered parameter
[21](https://github.com/ruby-git/ruby-git/actions/runs/4380304214/jobs/7667220593#step:4:22)
[warn]: Stack trace:
[22](https://github.com/ruby-git/ruby-git/actions/runs/4380304214/jobs/7667220593#step:4:23) …
```

Do not generate yard documentation when building in TruffleRuby

---

README.md
lib/git/lib.rb
tests/units/test_remotes.rb

Hey! Thanks for maintaining this awesome gem. This is my PR here, it's to add support for the [`--update-head-ok` (or `-u`) option](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt--u) to '#fetch`. Looking forward to (hopefully) getting this shipped! 🚢

Add support for `--update-head-ok` to `fetch`

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.17.2..v1.18.0)
Changes since v1.17.2:
* 3c70 Add support for `--update-head-ok` to `fetch` (#660)
* b53d Do not generate yard documentation when building in TruffleRuby (#659)
* 5af1 Correctly report command output when there is an error (#658)
* b27a Add test to ensure that `Git.open` works to open a submodule (#655)
* 5b0e Update Git.clone to set multiple config variables (#653)

Release v1.18.0

---

README.md
lib/git.rb
lib/git/lib.rb
tests/units/test_git_clone.rb

Add in support for `git clone --filter` option so you can do partial clones with. For example, `Git.clone(..., filter: 'tree:0')` would result in `git clone ... --filter=tree:0`

Add --filter to Git.clone for partial clones

---

lib/git/lib.rb
tests/units/test_lib.rb
tests/units/test_repack.rb
tests/units/test_worktree.rb

git-2.42.0 changes the behavior of `git worktree add` when there are no commits in the repository. Prior to 2.42.0, an error would result with creating a new worktree. Starting wtih 2.42.0, git will create an orphan branch for the worktree.
This PR also adds `Git::Lib#compare_version_to(other_version)` which return -1 if the git command version is less than the other_version, 0 if equal, and 1 if greater than.
This PR rewrites tests/units/test_repack.rb to make sure that the correct git command was called without error when Git::Lib#repack is called. Prior to this change, the test actually checked to see if the size of the repository was less after calling repack which was not always the case in the tests.

Update test of 'git worktree add' with no commits

---

tests/units/test_remotes.rb

`TestRemotes#test_push` fails depending on the git configuration `push.default` if an explicit remote branch name is not given. In particular, values of `upstream` or `tracking` values would make the test fail.
In order not to depend on this setting, explicitly name the remote branch to push to. This is not relevant to the test.

Explicitly name remote tracking branch in test

---

git.gemspec
lib/git/lib.rb
tests/test_helper.rb
tests/units/test_tree_ops.rb

Refactor tests in test/units/test_tree_ops.rb for Git::Lib#read_tree, write_tree, and commit_tree.
This is to fix these tests from failing on JRuby on Windows for PR #673 after some changes were made to remove calls to `Dir.chdir`. I believe the tests were failing due to how temporary directories were created and doing that in JRuby on Windows caused git to error out.
The refactor consists of limiting the tests to make sure that when the previously mentioned Git::Lib methods are called, that git is called with the right arguments without actually running git. In other words, the tests test this lib and not git itself or edge cases of the platform it is …

Refactor tests for Git::Lib methods #read_tree, #write_tree, and #commit_tree

---

lib/git.rb
lib/git/base.rb
lib/git/lib.rb
lib/git/status.rb
tests/units/test_commit_with_gpg.rb
tests/units/test_lib.rb

In multithreaded environment Dir.chdir changes current directory of all process' threads, so other threads might misbehave.
Base#chdir, Base#with_working and Base#with_temp_working were left intact, cause they are not used internally, so it's an explicit user decision to use them.
Fixes https://github.com/ruby-git/ruby-git/issues/355

Remove calls to Dir.chdir

---

README.md
lib/git/lib.rb
tests/units/test_push.rb

Add the ability to push all local branches to a specific remote repository.
```ruby
git.push('origin', all: true)
```

Add option to push all branches to a remote repo at one time

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.18.0..v1.19.0)
Changes since v1.18.0:
* 3bdb280 Add option to push all branches to a remote repo at one time (#678)
* b0d89ac Remove calls to Dir.chdir (#673)
* e64c2f6 Refactor tests for read_tree, write_tree, and commit_tree (#679)
* 0bb965d Explicitly name remote tracking branch in test (#676)
* 8481f8c Document how to delete a remote branch (#672)
* dce6816 show .log example with count in README, fixes #667 (#668)
* b1799f6 Update test of 'git worktree add' with no commits (#670)
* dd5a24d Add --filter to Git.clone for partial clones (#663)

Release v1.19.0

---

README.md
git.gemspec

Announce the 2.0.0 pre-release in the README.
git 2.0.0 is available as a pre-release version for testing! Please give it a try.
**JRuby on Windows is not yet supported by the 2.x release line. Users running JRuby
on Windows should continue to use the 1.x release line.**
The changes coming in this major release include:
* Create a policy of supported Ruby versions to support only non-EOL Ruby versions
* Create a policy of supported Git CLI versions (released 2020-12-25)
* Update the required Ruby version to at least 3.0 (released 2020-07-27)
* Update the required Git command line version to at least 2.28
* Update how CLI commands are called to use the [process_executer](https://github.com/main-branch/process_executer)
gem which is built on top of …

Announce the 2.0.0 pre-release

---

.github/workflows/continuous_integration.yml
README.md
git.gemspec
lib/git/lib.rb

The following changes were made in this PR:
* Update min supported Ruby version to 3.0.0
* Update min supported Git CLI version to 2.28.0
* Document supported Ruby policy in the README
* Update dependencies to latest versions
* Make a few tweaks to the README

Update minimum required version of Ruby and Git

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.19.1..v2.0.0-pre.1)
Changes since v1.19.1:
* 7585c39 Change how the git CLI subprocess is executed (#684)
* f93e042 Update instructions for releasing a new version of the git gem (#686)
* f48930d Update minimum required version of Ruby and Git (#685)

Release v2.0.0-pre.1

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.19.1..v2.0.0.pre1)
Changes since v1.19.1:
* 7585c39 Change how the git CLI subprocess is executed (#684)
* f93e042 Update instructions for releasing a new version of the git gem (#686)
* f48930d Update minimum required version of Ruby and Git (#685)

Release v2.0.0.pre1

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.0.0.pre1..v2.0.0.pre2)
Changes since v2.0.0.pre2:
* 023017b Add a timeout for git commands (#692)
* 8286ceb Refactor the Error heriarchy (#693)

Release v2.0.0.pre2

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_pull.rb

Add support options for `git.pull(...)` command. For example, `git.pull(origin, branch, allow_unrelated_histories: true)` would result in `git pull origin branch --allow-unrelated-histories`
Also extended the documentation for the `#pull` method

allow to pass options to pull comand

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.0.0.pre2..v2.0.0.pre3)
Changes since v2.0.0.pre2:
* 5d4b34e Allow allow_unrelated_histories option for Base#pull

Release v2.0.0.pre3

---

README.md

- Adds some more detail to the README for the log function, specifically around combining with other filters.
`.log.since` respects the default count configuration which makes sense but isn't clear in the examples or the docs. 
Perhaps naively I expected `g.log.since('1 month ago')` to return a whole month's worth of commits. Instead it consistently returned 30 which is the default for the `count` param.  To return a whole month you have to also specify a greater maximum i.e. `g.log(1000).since('1 month ago')` depending on the amount of activity in the repository.

Show log(x).since combination in README

---

README.md

- Adds some more detail to the README for the log function, specifically around combining with other filters.
`.log.since` respects the default count configuration which makes sense but isn't clear in the examples or the docs. 
Perhaps naively I expected `g.log.since('1 month ago')` to return a whole month's worth of commits. Instead it consistently returned 30 which is the default for the `count` param.  To return a whole month you have to also specify a greater maximum i.e. `g.log(1000).since('1 month ago')` depending on the amount of activity in the repository.

Show log(x).since combination in README (1.x)

---

.github/workflows/continuous_integration.yml
.github/workflows/experimental_continuous_integration.yml

The following builds are considered experimental:
* jruby-head on Windows (until jruby/jruby#7515 is fixed)
* ruby-head
Remove them from the main CI workflow so that PRs show that 100% of builds passed. Make experimental builds only run when something is merged to master (or the experimental workflow is run manually).

Move experimental builds out of the CI workflow and into their own workflow

---

README.md
bin/command_line_test
lib/git/command_line.rb
lib/git/lib.rb

Updates are to documentation only. No code was changed.
* More precisely described when timeouts can be specified and what impact they have: the git command is killed and a Git::TimeoutError is raised.
* Describe the global timeout vs. method timeouts
* Update `bin/command_line_test` to be able to sleep for a specific number of seconds to test timeouts.
* Update YARD doc to indicate that the timeout value is a Numeric or nil.
* Update Git.clone YARD doc

Update documentation for new timeout functionality

---

git.gemspec

Update create_github_release dependency so pre-releases can be made. Prior to 1.4.0, there was a bug when using prerelease versions.

Update create_github_release dependency so pre-releases can be made

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://jcouball@github.com/ruby-git/ruby-git/compare/v2.0.0.pre3..v2.0.0.pre4)
Changes since v2.0.0.pre3:
* 56783e7 Update create_github_release dependency so pre-releases can be made
* 8566929 Add dependency on create_github_release gem used for releasing the git gem
* 7376d76 Refactor errors that are raised by this gem
* 7e99b17 Update documentation for new timeout functionality
* 705e983 Move experimental builds to a separate workflow that only runs when pushed to master
* e056d64 Build with jruby-head on Windows until jruby/jruby#7515 is fixed
* ec7c257 Remove unneeded scripts to create a new release
* d9570ab Move issue and pull request templates to the .github directory
* e4d6a77 Show log(x).since combination in README

Release v2.0.0.pre4

---

.github/pull_request_template.md
CONTRIBUTING.md

Remove the requirement for DCO sign-off. 
This project has implemented an automated check for the presence of a sign-off but nothing to check it's authenticity or the contributor's understanding. In order to provide the intended robust legal protection, a mechanism would have to be put into place to track that contributors have understood what putting the sign-off in the commit message and add them to a "committer whitelist".
[Truffle Ruby](https://github.com/oracle/truffleruby), for example, requires that all contributors sign an [Oracle Contributor Agreement](https://oca.opensource.oracle.com) before they are allowed to contribute to their repository.
Rather than implement a more formalized and heavier process to track these attestations, DCO shall be removed from this project.
In my …

Remove the DCO requirement for commits

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.0.0.pre4..v2.0.0)
Changes since v2.0.0.pre4:
* 1afc4c6 Update 2.x release line description
* ed52420 Make the pull request template more concise
* 299ae6b Remove stale bot integration
* efb724b Remove the DCO requirement for commits

Release v2.0.0

---

lib/git/lib.rb
lib/git/status.rb
tests/units/test_status.rb

Review our [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository. A good start is to:
* Write tests for your changes
* Run `rake` before pushing
* Include / update docs in the README.md and in YARD documentation
Fixes #422
The original implementation was needed for older versions of Git. Now that we are supporting newer versions, we can use the following method to get untracked files which changes the directory to the worktree root directory:
`command_lines('ls-files', '--others', '--exclude-standard', chdir: @git_work_dir)`

Fix Git::Status#untracked when run from worktree subdir

---

lib/git/lib.rb
lib/git/status.rb
tests/units/test_lib.rb
tests/units/test_status.rb

Review our [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository. A good start is to:
* Write tests for your changes
* Run `rake` before pushing
* Include / update docs in the README.md and in YARD documentation
Git::Base#status on an empty repo throws an exception. To determine the files that were added, a diff is done between the index and HEAD revision. However, in an empty repository, HEAD does not exist and diffing returns an error.
This PR makes a change to check if the repository is empty before trying to do the diff. Git::Lib#empty? is introduced to determine if the repository is empty (i.e. it has no commits).
Fixes #422

Fix Git::Base#status on an empty repo

---

README.md
lib/git/status.rb
tests/units/test_status.rb
tests/units/test_status_object.rb
tests/units/test_status_object_empty_repo.rb

This PR codifies what the Git::Status class does via unit test assertions to see what is returned for different states of the repository, index, and worktree. In addition to documenting what Git::Status actually does, I have noted in each test what the `git status` command line would return in the same scenario and where I think Git::Status is wrong (search for ERROR: in the test files).
This PR does not change the implementation of Git::Status.
The Git::Status class tries to add functionality over the top of the `git status` command and returns surprising and often incorrect results. However, it was not obvious what is **SHOULD** return even upon inspecting the code. 
If I had to try summarize it: Git::Status tries to merge the functionality of `git ls-files` (which lists ALL files in …

Document and add tests for Git::Status

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.0.0..v2.0.1)
Changes since v2.0.0:
* da435b1 Document and add tests for Git::Status
* c8a77db Fix Git::Base#status on an empty repo
* 712fdad Fix Git::Status#untracked when run from worktree subdir
* 6a59bc8 Remove the Git::Base::Factory module

Release v2.0.1

---

README.md
lib/git/log.rb
tests/units/test_log.rb

Fixes #725 
This PR contains two related changes:
* Adds ability for Git::Log#initialize to accept `:all` (in addition to `nil`) to indicate there is no maximum number of commits. This means that Git::Base#log can be called with `:all` as well.
```ruby
git.log(:all) #=> return all commits that `git log` would return
```
* Adds ability to specify the maximum number of commits returned with `Git::Log#max_count` which can take a number or :all or nil to return all commits that match the specified criteria
```ruby
git.log.max_count(:all) #=> return all commits that `git log` would return
git.log
.max_count(:all)
.object('README.md')
.since('10 years ago')
.between('v1.0.7', 'HEAD')
.map { |commit| commit.sha }
```
Note that calling `git.log(:all)` and `Git::Log.new(git, …

Add Git::Log#max_count

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.0.1..v2.1.0)
Changes since v2.0.1:
* 93c8210 Add Git::Log#max_count
* d84097b Update YARDoc for a few a few method

Release v2.1.0

---

lib/git/status.rb
tests/units/test_status.rb

Fixes #586 by making `Status#changed?` case-insensitive when `core.ignoreCase` is set. Also solve the matching unreported issues for `Status#added`, `Status#deleted`, and `Status#untracked`.
I did run into a bit of an issue trying to write thorough tests for these, because it turns out that _git itself_ doesn't support setting `core.ignoreCase` to a value that doesn't match the behavior of the file-system; [that option](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase) is provided so you can tell git how the file-system is going to act, not so you can control git's behavior! In the tests here, I do break that guideline, but because I don't actually rename any files, `git` doesn't have trouble - just don't try to make it test the case that was actually …

When core.ignorecase, check Status for files case-insensitively

---

lib/git/lib.rb
tests/files/working/dot_git/config

Previously, we were supplying `color.ui=false`, but if the local gitconfig specified any of the more specific options (like `color.diff`), those would take precedence. This updates our command-runner to always supply all of the specific color options as false as well, so that we definitely get a color-free output suitable for parsing.
Updating the fixture causes several of the existing specs to fail without the code changes (especially the `diff` tests), which is probably an appropriate level of testing - I doubt all of these config options are actually necessary, but I don't see any harm in including them.
This should replace #723, since that won't be necessary anymore. We don't currently have any tests checking the actual contents of the commands being run, but I _could_ rig up a test …

Supply all of the _specific_ color options too

---

lib/git/base.rb
lib/git/escaped_path.rb
lib/git/lib.rb
tests/units/test_ignored_files_with_escaped_path.rb

Fixes #694
This is a bug fix: if a repository contains ignored files with non-ASCII or otherwise “unusual” characters that trigger [quotePath](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corequotePath), then Git.open(…).lib.ignored_files currently returns the git-quoted paths, not the proper filenames.
This PR properly unescapes the paths returned from `git ls-files` called from Git::Lib#ignore_files.

Handle ignored files with quoted (non-ASCII) filenames

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.1.0..v2.1.1)
Changes since v2.1.0:
* 6ce3d4d Handle ignored files with quoted (non-ASCII) filenames
* dd8e8d4 Supply all of the _specific_ color options too
* 749a72d Memoize all of the significant calls in Git::Status
* 2bacccc When core.ignoreCase, check for untracked files case-insensitively
* 7758ee4 When core.ignoreCase, check for deleted files case-insensitively
* 993eb78 When core.ignoreCase, check for added files case-insensitively
* d943bf4 When core.ignoreCase, check for changed files case-insensitively

Release v2.1.1

---

README.md
lib/git/base.rb
lib/git/lib.rb
tests/units/test_ls_tree.rb

Enables `git ls-tree -r head` which lists the contents of a tree object, recursively.
`git ls-files` isn't appropriate since it includes files in the index and the working tree.

ls-tree optional recursion into subtrees

---

lib/git/lib.rb
tests/units/test_diff.rb

Verify that the commit arguments to Git::Base#diff do not resemble command-line options. Passing a commit that begins with a hyphen will result in an ArgumentError being raised.
For instance:
```
commit = 'HEAD'
git.diff(commit)
```
Would execute:
```
git diff HEAD
```
However, if the commit is something that looks like a command line option, such as '-s', then the following command line would be executed:
```
git diff -s
```
Which probably isn't what was wanted/expected. After this change, the above statement would raise an ArgumentError.

Verify that the commit(s) passed to git diff do not resemble a command-line option

---

lib/git/lib.rb
tests/units/test_describe.rb

Verify that the commit-ish argument to Git::Base#describe does not resemble a command-line. Passing a commit-ish that begins with a hyphen will result in an ArgumentError being raised.
For instance:
```
commit = 'HEAD'
git.describe(commit)
```
Would execute:
```
git describe HEAD
```
However, if the commit is something that looks like a command line option, such as '--all', then the following command line would be executed:
```
git diff --all
```
Which probably isn't what was wanted/expected. After this change, the above statement would raise an ArgumentError.

Verify that the commit-ish passed to git describe does not resemble a command-line option

---

lib/git/lib.rb
tests/units/test_lib.rb

Verify that the revision range to git log does not resemble a command-line. Passing a revision range (via the :object or :between options) that begins with a hyphen will result in an ArgumentError being raised.
For instance:
```
git.lib.log_commits(object: '--all')
```
Would execute:
```
git log --all
```
Which probably isn't what was wanted/expected. After this change, the above statement would raise an ArgumentError.

Verify that the revision-range passed to git log does not resemble a command-line option

---

README.md
lib/git/base.rb
lib/git/lib.rb
lib/git/object.rb
tests/units/test_branch.rb
tests/units/test_lib.rb
tests/units/test_object.rb

Make the following changes to Git::Lib#rev_parse:
* Remove optimizations that try to calculate the resulting SHA instead of calling `git rev-parse`. This library should not reimplement git functionality if possible. Git could change and then the assumptions in these optimizations would no longer be valid (e.g. SHAs are 40 digit hex numbers).
There is a chance that this could break existing uses if the optimization implementation is already different than the implementation of `git rev-parse`
* Validate that the reference passed in does not look like a command-line option (i.e. starts with a hyphen).

Refactor Git::Lib#rev_parse(revision) and sanitize its input

---

lib/git/lib.rb
lib/git/object.rb
tests/units/test_lib.rb

Sanitize the commit_ish argument passed to Git::Lib#name_rev.
Before this change, the following method call:
```
lib.name_rev('--all')
```
would result in `git name-rev --all` which is not the intention.
After this change, passing a commit-ish that looks like a command-line option (aka starts with a hyphen) will cause an ArgumentError to be raised.

Sanitize non-option arguments passed to `git name-rev`

---

tests/test_helper.rb
tests/units/test_signed_commits.rb

During the Windows MRI Ruby 3.0 build, the following error occurs:
```text
error: Couldn't load public key D:/a/_temp/d20240826-5256-oy57bv/.git/test-key.pub: No such file or directory?
fatal: failed to write commit object
```
This is due to signed commits not being setup correctly in the Windows testing. This is not an issue with the git gem, but an issue with how the test sets up commit signing on Windows.
This test is about how the output from `git cat-file` is handled by the git gem. If this functionality works on Linux, it should work on Windows.

Omit testing of Git::Lib#commit_data to retrieve gpg sig of signed commits on Windows

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.1.1..v2.2.0)
Changes since v2.1.1:
* 7292f2c Omit the test for signed commit data on Windows
* 2d6157c Document this gem's (aspirational) design philosophy
* d4f66ab Sanitize non-option arguments passed to `git name-rev`
* 0296442 Refactor Git::Lib#rev_parse
* 9b9b31e Verify that the revision-range passed to git log does not resemble a command-line option
* dc46ede Verify that the commit-ish passed to git describe does not resemble a command-line option
* 00c4939 Verify that the commit(s) passed to git diff do not resemble a command-line option
* a08f89b Update README
* 737c4bb ls-tree optional recursion into subtrees

Release v2.2.0

---

lib/git/base.rb
lib/git/lib.rb
tests/units/test_branch.rb

Fixes #742
If you get into a detached HEAD state, calling ::Git.open('.').branch throws an error.
This PR changes Git::Base#branch to return a branch object whose #name is 'HEAD'.

Make Git::Base#branch work when HEAD is detached

---

lib/git/base.rb
lib/git/lib.rb
lib/git/object.rb
tests/units/test_lib.rb
tests/units/test_object.rb
tests/units/test_signed_commits.rb

Sanitize the object reference sent to the cat-file command.
Make sure the object reference sent to cat-file commands do not start with a hyphen so they are not mistaken for command line options.
Also normalize the cat-file commands in accordance with [this project's design philosophy](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md#design-philosophy). This includes adding the following commands (and aliases):
* #cat_file_contents was aliased to #object_contents
* #cat_file_type was aliased to #object_type
* #cat_file_size was aliased to #object_size
* #cat_file_commit was aliased to #commit_data
* #cat_file_tag was aliased to #tag_data

Sanatize object ref sent to cat-file command

---

lib/git/lib.rb
tests/units/test_lib.rb
tests/units/test_logger.rb

Adjust the quoting in a shell command in a test that made the windows build fail.
Ignore error on windows where the test finalizer fails to remove files that were already removed.
Fix a Yardoc error.

Fix windows CI build

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.2.0..v2.3.0)
Changes since v2.2.0:
* f8bc987 Fix windows CI build error
* 471f5a8 Sanatize object ref sent to cat-file command
* 604a9a2 Make Git::Base#branch work when HEAD is detached

Release v2.3.0

---

CONTRIBUTING.md
lib/git.rb
lib/git/base.rb
tests/units/test_git_binary_version.rb

Add Git.binary_version to get the version of the git command line without having to open a repository.

Add Git.binary_version to return the version of the git command line

---

CONTRIBUTING.md

The instructions were re-written for clarity.

Update instructions for building a specific version of Git

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.3.0..v2.3.1)
Changes since v2.3.0:
* e236007 test: allow bin/test-in-docker to accept the test file(s) to run on command line
* f4747e1 test: rename bin/tests to bin/test-in-docker
* 51f781c test: remove duplicate test from test_stashes.rb
* 2e79dbe Fixed "unbranched" stash message support:
* da6fa6e Conatinerised the test suite with Docker:
* 2e23d47 Update instructions for building a specific version of Git
* 70565e3 Add Git.binary_version to return the version of the git command line

Release v2.3.1

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.3.1..v2.3.2)
Changes since v2.3.1:
* 7646e38 fix: improve error message for Git::Lib#branches_all

Release v2.3.2

---

tests/test_helper.rb
tests/units/test_branch.rb

Add the method `#run_command` to `tests/test_helper.rb` so it is available to all tests.
This method is to be used in tests in place of using backticks for running shell commands (like git). This method has the following advantages:
* shell quoting and escaping is not necessary as it is with backticks - this is particularly bothersome to get right in a cross platform way)
* a timeout can be specified (by passing `timeout: value`)
* both stdout and stderr are captured and returned along with the process status in a `CommandResult` object (see below)
* by default an error is raised when the command returns a non-zero exit code (this can be turned off by passing `raise_errors: false`) - to eliminate silent errors because the backtick exit status was not checked.
This method returns a …

test: add `#run_command` for tests to use instead of backticks

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.3.2..v2.3.3)
Changes since v2.3.2:
* c25e5e0 test: add tests for spaces in the git binary path or the working dir
* 5f43a1a fix: open3 errors on binary paths with spaces
* 60b58ba test: add #run_command for tests to use instead of backticks

Release v2.3.3

---

.github/workflows/continuous_integration.yml

Add support for Ruby 3.4 while removing support for Ruby 3.0 in the testing matrix. Adjustments made to ensure compatibility with the latest Ruby version.

Support Ruby 3.4 and drop Ruby 3.0 support

---

bin/command_line_test
lib/git/command_line.rb
tests/units/test_command_line.rb
tests/units/test_logger.rb

Replace custom implementation of git command execution with `ProcessExecuter.run` and update tests to reflect these changes.
* Functionality to build the git command and process its output will remain in `Git::CommandLine`
* Functionality to run a git command in a subprocess and collect its output will be handled by `ProcessExecuter.run`

Refactor Git::CommandLine to use ProcessExecuter.run

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v2.3.3..v3.0.0)
Changes since v2.3.3:
* 534fcf5 chore: use ProcessExecuter.run instead of the implementing it in this gem
* 629f3b6 feat: update dependenices
* 501d135 feat: add support for Ruby 3.4 and drop support for Ruby 3.0
* 38c0eb5 build: update the CI build to use current versions to TruffleRuby and JRuby
* d3f3a9d chore: add frozen_string_literal: true magic comment

Release v3.0.0

---

lib/git/lib.rb
tests/test_helper.rb
tests/units/test_command_line_env_overrides.rb

Set the locale when running git commands to en_US.UTF-8 to ensure that git output is untranslated (aka English). This ensures that the git command output can consistently be parsed by this gem.
A test was added to verify that command line environment variables are set correctly when executing commands. This includes enhancements to the assert_command_line_eq method to accommodate environment variable checks.
Fixes #753

Set the locale when running git commands to en_US.UTF-8

---

lib/git/lib.rb
tests/units/test_lib.rb

Improved error message of rev_parse
As described by git-rev-parse:
```
Many Git porcelainish commands take mixture of flags (i.e. parameters
that begin with a dash -) and parameters meant for the underlying git
rev-list command they use internally and flags and parameters for the
other commands they use downstream of git rev-list. This command is
used to distinguish between them.
```
Using the `--` to separate revisions from paths is at the core of git. I do not think this behavior will ever change.
The message without the extra parameters:
```
fatal: ambiguous argument 'v3': unknown revision or path not in the
working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
The message with new parameters:
```
fatal: bad revision …
```

Improved error message of rev_parse

---

CHANGELOG.md
lib/git/version.rb

[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v3.0.0..v3.0.1)
Changes since v3.0.0:
* b47eedc Improved error message of rev_parse
* 9d44146 chore: update the development dependency on the minitar gem
* f407b92 feat: set the locale to en_US.UTF-8 for git commands
* b060e47 test: verify that command line envionment variables are set as expected
* 1a5092a chore: release v3.0.0

Release v3.0.1

---

.commitlintrc.yml
.gitignore
.husky/commit-msg
CONTRIBUTING.md
bin/setup
package.json

- Add steps to bin/setup to install husky and the commitlint npm packages
- Configure husky to run commitlint via the commit-msg hook
- Add commitlint configuration based on my specific preferences
- Add npm specific files (node_modules/, package-lock.json) to .gitignore
This partially addresses issue #791.

Enforce conventional commit messages with husky and commitlint

---

.github/workflows/enforce_conventional_commits.yml

- Add a GitHub Actions workflow to enforce conventional commits
- Add commitlint configuration based on my specific preferences
Partially addresses issue #791

Enforce conventional commit messages with GitHub Action

---

.github/workflows/release.yml

Update the release workflow to trigger on changes to the 'master' branch instead of 'main'.

Change release workflow trigger branch to master

---

CONTRIBUTING.md
README.md

This PR introduces two changes:
- Announce the adoption of conventional commits in the README.md
- Document the project's use of conventional commits in CONTRIBUTING.md
This further refines issue #791

Document guidelines for Conventional Commits

---

lib/git/lib.rb
lib/git/log.rb
tests/test_helper.rb
tests/units/test_log.rb

Introduce the ability to filter commits to only include merge commits when using Git::Base#log. 
Example:
```Ruby
log = git.log
.max_count(:all)
.merges
```
This enhancement adds a new method to the Git::Log class to enable this functionality and updates the relevant log commands accordingly.
Since the `--merges` option to `git log` only filters the results, I thought it was sufficient to just test that the option was added to the git log command when appropriate.
Fixes #788

Support for git log --merges option

---

.github/workflows/continuous_integration.yml

Modify the CI workflow to skip execution for pull requests that are based on release PRs created by the release-please-action.
CI for these changes were already run twice: once for the PR and once after being merged to master.

Skip CI for release PRs

---

.github/workflows/continuous_integration.yml
.github/workflows/experimental_continuous_integration.yml

Modify the CI configuration to skip the experimental build workflow when a release commit is pushed to the master branch. This change streamlines the build process by avoiding unnecessary builds for release-related commits.

Skip experimental build workflow for release PRs

---

lib/git/base.rb
lib/git/diff.rb
lib/git/diff_path_status.rb
lib/git/diff_stats.rb
lib/git/lib.rb
tests/units/test_diff.rb
tests/units/test_diff_path_status.rb
tests/units/test_diff_stats.rb

This pull request refactors the `Git::Diff` class decomposing it into new, more focused classes, while backward compatibility is maintained via a deprecated facade.
* **Decomposed `Git::Diff`**: The original `Git::Diff` class, which handled full patch parsing, statistics, and name-status, has been refactored. Its core responsibility is now limited to parsing a full diff patch and providing an enumeration of DiffFile objects.
* **New `Git::DiffStats` Class**: A new `Git::DiffStats` class has been introduced to exclusively handle the logic for `git diff --numstat`, providing access to insertion/deletion counts and file-level statistics.
* **New `Git::DiffPathStatus` Class**: A new `Git::DiffPathStatus` class now manages the output of `git diff --name-status`, providing a clear mapping of …

Refactor Git::Diff to separate classes for DiffStats and DiffPathStatus

---

tests/units/test_signed_commits.rb

Running tests on a very modern system results in 
```
ssh-keygen -t dsa
unknown key type dsa
```
with OpenSSH_9.9p1

Avoid deprecated dsa for tests keys

---

.rubocop.yml
.rubocop_todo.yml
lib/git/command_line.rb

Most of these offenses were fixed by excluding tests from this metric. This is fine since I plan on moving tests to RSpec in the near future.
The other few instances were fixed by refactoring the methods.

Fix Rubocop Metrics/AbcSize offense

---

Rakefile
lib/git/base.rb

I was getting a lot of deprecation warnings from inside this gem, but when I tracked them down, they were actually just an internal call, and also deprecated internally. Easy fix :-)
`Git.open(".")` can reproduce the issue on 4.0.1:
* `Git.open` calls `Git::Base.open`
* which calls the initializer (on line 129)
* which calls `initialize_components` (line 157)
* which calls `Git::Index.new` with a second positional parameter
* but `Git::Index` is a straight subclass of `Git::Path`, which warns us about the positional parameter
I started to open an issue, and then decided that was silly - this is a trivial fix. (Though I guess I'll need to wait for a gem release to escape the cli noise)
While exercising it, I also noticed that the comments in Rakefile describing how to run individual tests …

Don't trigger our own deprecation warning

---

lib/git/path.rb
lib/git/stash.rb
tests/test_helper.rb
tests/units/test_log_deprecations.rb
tests/units/test_object_new.rb
tests/units/test_set_index.rb
tests/units/test_set_working.rb

Eliminate deprecation warnings from internal Git classes.
Add tests that verify that when deprecated methods are called, the deprecation warning is given.
Also, add tests for Base#set_index and Base#set_working.

Add tests for deprecations

---

README.md
redesign/1_architecture_existing.md
redesign/2_architecture_redesign.md
redesign/3_architecture_implementation.md

The git gem is undergoing a significant architectural redesign for the upcoming
v5.0.0 release. The current architecture has several design challenges that make it
difficult to maintain and evolve. This redesign aims to address these issues by
introducing a clearer, more robust, and more testable structure.
We have prepared detailed documents outlining the analysis of the current
architecture and the proposed changes. We encourage our community and contributors to
review them:
1. [Analysis of the Current Architecture](redesign/1_architecture_existing.md): A
breakdown of the existing design and its challenges.
2. [The Proposed Redesign](redesign/2_architecture_redesign.md): An overview of the
new three-layered architecture.
3. [Implementation …

Document and announce the proposed architectural redesign
