- lib/git/base.rb
- lib/git/lib.rb
workig => working
dorectory => directory
> fix typo in documentation

- lib/git/diff.rb
- lib/git/lib.rb
Fix the encoding issue - 'split': invalid byte sequence in UTF-8 (Argument Error) #190 - from up-to-date master
> Fix the encoding issue - 'split': invalid byte sequence in UTF-8 (up-to-date!!)

- lib/git/status.rb
- tests/units/test_status.rb
- tests/units/test_thread_safty.rb
> adding boolean functions for git status

- .travis.yml
Jruby build is broken. This is an attempt to fix it.
> Tweaking yaml build to reveal git version

- .github/stale.yml
This should let us get rid of some of the older issues with very little work. What do you think of the idea?
For reference: https://github.com/probot/stale
> Added probot stale config

- lib/git/lib.rb
> Fix UTF-8 message errors

- lib/git/lib.rb
- tests/units/test_init.rb
c.f. https://help.github.com/articles/duplicating-a-repository
Updating original PR #167 from
Author:    Lars Schneider <larsxschneider@gmail.com>
Date:      Sat Aug 9 23:24:41 2014 -0700
> Enable mirror option for git clone and push

- README.md
- lib/git/branch.rb
- lib/git/lib.rb
- tests/units/test_branch.rb
This allows the user to see if an arbitrary commit is contained within a
branch. For example you can check to see if a branch was merged into
master with `git.branch('master').contains?('feature')`. Or you can see
if your feature branch has the latest master commit with
`git.branch('feature').contains?('master')`
> Check if branch contains commit

- lib/git/lib.rb
- tests/units/test_lib.rb
Honor `git commit --date=...` flag.
Re-submitting the stalled #315
> commit with custom author date

- lib/git/lib.rb
- tests/units/test_lib.rb
Signed-off-by: Stephen Paul Weber <singpolyma@singpolyma.net>
Allow passing the `--unshallow` option
> Add support for unshallow

- CONTRIBUTING.md
The intent was to structure the instructions better without making actual changes to the contribution rules.
> Update instructions for making contributions

- MAINTAINERS.md
- RELEASING.md
* Since I am not a maintainer, add myself to [MAINTAINERS.md](https://github.com/ruby-git/ruby-git/blob/a107e878727e76f01f2d4b4ad3bda0068bcc63ee/MAINTAINERS.md)
* Document release instructions for future maintainers in RELEASING.md
> Add new maintainer and add release instructions

- CHANGELOG.md
- lib/git/version.rb
Create the v1.6.0 release of the git gem.
> Release v1.6.0

- lib/git/lib.rb
fix #429 , make implementation work like documentation states it
> Fix describe command's dirty, abbrev, candidates, and match options

- README.md
Better for high DPI screens / scaling
Use https for badge fury url to decrease redirects
> Use SVG Badge for Gem Version in README.md

- CHANGELOG.md
- lib/git/version.rb
Bump version and update CHANGELOG.md for 1.6.1 release.
[Full Changelog](https://github.com/jcouball/ruby-git/compare/v1.6.0...v1.7.0)
* 2302673 Release v1.7.0
* b8c6320 Disable GPG Signing in Test Config (#467)
* 861eb71 Add no verify for commit with documentation (#454)
* f3b439d Fix hash keys in #describe (#415)
* 9f8e1c8 README: Use SVG Badge (#457)
* 5391aef Git::Lib#normalize_encoding early return fix (#461)
* 2b9629d Remove extraneous '--' from `git stash save -- message`
* af4902b Fix Ruby 2.7 Deprecation Warning About Keyword Args (#453)
* c10ca28 Fix issue with color escape codes after recent update of `git` binaries (#427)
* c85dd82 Fix describe …
> Release v1.7.0

- .travis.yml
Please describe your pull request.
Just added Ruby Version 2.7 to the Travis-CI build.
> Added ruby-2.7 to .travis.yml

- CHANGELOG.md
- lib/git/version.rb
Bump version and update CHANGELOG.md for 1.8.0 release.
> Release v1.8.0

- CHANGELOG.md
- lib/git/version.rb
Bump version and update CHANGELOG.md for 1.8.1 release.
> Release v1.8.1

- CHANGELOG.md
- lib/git/version.rb
Signed-off-by: James Couball <couballj@verizonmedia.com>
Bump version to build a 1.9.0 release.
> Release v1.9.0

- CHANGELOG.md
- lib/git/version.rb
Signed-off-by: James Couball <couballj@verizonmedia.com>
Bump version to build a 1.9.1 release.
> Release v1.9.1

- lib/git/lib.rb
Signed-off-by: Alexande B <abobrikovich@gmail.com>
🚨 Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.
#533
> #533 Add --depth options for fetch call

- CHANGELOG.md
- lib/git/version.rb
Bump version to build a 1.10.0 release.
> Release v1.10.0

- CHANGELOG.md
- lib/git/version.rb
* c7b12af Release v1.10.1
* ea28118 Properly escape double quotes in shell commands on Windows (#552)
* db060fc Properly unescape diff paths (#504)
* ea47044 Add Ruby 3.0 to CI build (#547)
* cb01d2b Create a Docker image to run the changelog (#546)
> Release v1.10.1

- bin/console
- bin/create-release
- bin/setup
- git.gemspec
This PR adds the `bin/create-release` script which automates the following:
* Assert that all prerequisites for creating the release are met (see below)
* Create the release branch locally
* Update and commit the CHANGELOG.md and version.rb files
* Create the release tag
* Push the new commit and tag to the remote
* Create the GitHub release with the change log listing
* Create the release PR
This script checks the following prerequisites:
* The current directory is the top-level directory of the git repo with the default branch checked out
* There are no uncommitted changes in the work tree or staging area …
> Add a script to create the release of this gem

- CHANGELOG.md
- lib/git/version.rb
[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.10.1...v1.10.2)
* 57f941c Release v1.10.2
* c987a74 Add create-release, setup, and console dev scripts (#560)
* 12e3d03 Store tempfile objects to prevent deletion during tests (#555)
> Release v1.10.2

- MAINTAINERS.md
Signed-off-by: Vern Burton <me@vernburton.com>
- [ X Ensure that your contributions contain documentation if applicable.
Removing myself from a maintainer
> Remove myself from Maintainers

- CHANGELOG.md
- lib/git/version.rb
[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.11.0...v1.12.0)
* ea79dad Release v1.12.0
* e58cd29 Support the commit --no-gpg-sign flag (#589)
* 323383b Use yard gem version 0.9.8 or later instead of HEAD from GitHub (#592)
* 609ab8b Allow the CI build to be run manually using the GitHub interface (#590)
* 4a96679 Fix windows build (#591)
* 6f2b3fd Support the --all option for git fetch (#583)
* 1b13ec1 Workaround to get JRuby build working (#582)
* 5f0adec Update README.md (#580)
* 45b467c Make the directory param to Git.clone optional (#578)
* b92130c Make Git::URL.clone_to handle cloning to bare and mirror repos (#577)
* 13471d7 Add …
> Release v1.12.0

- MAINTAINERS.md
Add Frank Throckmorton to the list of maintainers.
> Add Frank Throckmorton to the list of maintainers

- RELEASING.md
- git.gemspec
Switch to using the [create-github-release](https://github.com/main-branch/create_github_release) script to create new releases of the git gem.
> Update release instructions

- lib/git/escaped_path.rb
- tests/units/test_escaped_path.rb
Please describe your pull request.
> Fix escaped path decoding

- lib/git/lib.rb
- tests/units/test_branch.rb
Fixes #474
`Git::Lib#all_branches` (silently) failed to correctly parse `git branch --all` output for branches that are symbolic references (like '    remotes/origin/HEAD -> origin/master').
This PR correctly parses the output of `git branch --all` and add a test case for the case of branches that are symbolic references.
> Fix parsing of symbolic refs in `Git::Lib#branches_all`

- README.md
Document how to use this API to delete a remote branch. Fixes #671
> Document how to delete a remote branch

- CHANGELOG.md
- lib/git/version.rb
[Full Changelog](https://github.com/ruby-git/ruby-git/compare/v1.19.0..v1.19.1)
Changes since v1.19.0:
* f97c57c Announce the 2.0.0 pre-release (#682)
> Release v1.19.1

- RELEASING.md
Releasing a new version of the `git` gem requires these steps:
* Install Prerequisites
* Determine the SemVer release type
* Create the release
* Review the CHANGELOG and release PR
* Manually merge the release PR
* Publish the git gem to RubyGems.org
This PR updates these instructions in RELEASING.md.
> Update instructions for releasing a new version of the git gem

- README.md
Update the README.md with details on the 2.x release line and remove discussion of 2.x pre-releases.
> Update 2.x release line description

- lib/git/base.rb
- lib/git/lib.rb
This pull request updates the YARDoc for a few methods in the codebase. The changes include adding missing documentation and improving the existing documentation for better clarity and understanding. Docs were updated for:
* Git::Base#add
* Git::Base#add_remote
* Git::Base#add_tag
* Git::Lib#initialize
Fixes #691
> Update YARDoc for a few a few methods

- lib/git/status.rb
When the status has many entries, there were substantial inefficiencies in this class - calling predicates like `changed?(filename)` would iterate the status, constructing a transient `changed` subhash, then test that subhash to see if the file in question was in it (for example).
After this change, it will _keep_ those sub-hashes for reuse on the Status instance, as well as `downcase`d versions if they happen to get requested (by case-insensitive calls).
> Memoize all of the significant calls in Git::Status

- CONTRIBUTING.md
Document the gem's design philosophy so that contributors and code reviewers can have some guidance on how the gem is (or should be) designed.
> Document this gem's (aspirational) design philosophy

- bin/test
- bin/tests
- lib/git/lib.rb
- tests/Dockerfile
- tests/docker-compose.yml
- tests/units/test_stashes.rb
A tiny fix, would appreciate a version ASAP. Thanks!
> saving colons in stash messages from crashes

- lib/git/lib.rb
- tests/units/test_lib.rb
When the output from `git branch -a` can not be parsed, return an error that shows the complete output, the line containing the error, and the line with the error.
Here is an example of the new error message:
```text
Unexpected line in output from `git branch -a`, line 2
Full output:
* (HEAD detached at origin/master)
this line should result in an Git::UnexpectedResultError
master
remotes/origin/HEAD -> origin/master
remotes/origin/master
Line 2:
"  this line should result in an Git::UnexpectedResultError"
```
> Improve error message for Git::Lib#branches_all

- lib/git/base.rb
Resolves #757 which is caused by `Open3` splitting the string by spaces. This is an issue when Git binaries exist in a path containing spaces like `C:\Program Files\Git\git.exe`
By splitting to `args` instead of a single string `Open3` is able to properly execute the command against the git binary. Switching to `capture2e` is required because `capture2` generates an error when `2&>1` is used. `capture2e` redirects `stderr` to `stdout` for us.
Because there is a possibility that `Open3` will now fail because the binary doesn't exist we have to handle the execution of `Open3` in a rescue block and raise the correct error type.
> fix: open3 errors on binary paths with spaces

- lib/git/base.rb
- tests/test_helper.rb
- tests/units/test_git_base_root_of_worktree.rb
- tests/units/test_git_binary_version.rb
Add tests for the changes submitted in #757
> test: add tests for spaces in the git binary path or the working dir

- git.gemspec
- tests/units/test_command_line.rb
Update dependencies. In particular, update to latest version of process_executer to get the new ProcessExecuter.run method which will remove some code in this project.
> feat: update dependenices

- git.gemspec
Update to version 1.x of the minitar gem
Fixes #732
> Update the development dependency on the minitar gem

- .github/pull_request_template.md
- .github/workflows/continuous_integration.yml
- .github/workflows/enforce_conventional_commits.yml
- .github/workflows/experimental_continuous_integration.yml
- .github/workflows/release.yml
- README.md
- bin/test
Create an announcement in the README and update the GitHub Actions workflows.
> Update the project's default branch from 'master' to 'main'

- lib/git/status.rb
> fix: fix typo in status.rb

- .rubocop.yml
- .rubocop_todo.yml
- lib/git/base.rb
Simply refactored to offending method by decomposing it.
> Fix Rubocop Metrics/CyclomaticComplexity offense
